/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interviewee;

import static interviewee.Screen.device;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_ESCAPE;
import java.awt.event.KeyListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nimesh
 */
public class firstscreen extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form firstscreen
     */
    static GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0];

    ServerSocket ss;
    Socket s;DataInputStream dis;
    
    public firstscreen() {
        this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setVisible(true);
//        this.setResizable(true);
        //device.setFullScreenWindow(this);
        initComponents();
        addKeyListener(this);
        setFocusable(true);
        setFocusTraversalKeysEnabled(true);
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regno = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Branch = new javax.swing.JTextField();
        College = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegnoActionPerformed(evt);
            }
        });
        Regno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegnoKeyPressed(evt);
            }
        });

        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameKeyPressed(evt);
            }
        });

        Branch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BranchKeyPressed(evt);
            }
        });

        College.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        College.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollegeActionPerformed(evt);
            }
        });
        College.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CollegeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CollegeKeyTyped(evt);
            }
        });

        Start.setText("Start Test");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        Start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StartKeyPressed(evt);
            }
        });

        jLabel1.setText("College");

        jLabel2.setText("Name");

        jLabel3.setText("Reg No.");

        jLabel4.setText("Branch");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        exit_btn.setText("Exit Test");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_btn))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_btn)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start)
                    .addComponent(Branch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(College, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(College, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(Regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(Branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegnoActionPerformed

    private void CollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CollegeActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
       try{
        s=new Socket("192.168.43.148",6669);  //172.29.44.250
        //        s=new Socket("localhost",6669);  //172.29.45.224
        System.out.println(1);
        DataOutputStream dout=new DataOutputStream(s.getOutputStream());
        
        dout.writeUTF(College.getText());  
        dout.flush();  
        dout.writeUTF(Regno.getText());  
        dout.flush();  
        dout.writeUTF(Name.getText());  
        dout.flush();  
        dout.writeUTF(Branch.getText());  
        dout.flush();       
        DataInputStream din=new DataInputStream(s.getInputStream());
        String str=din.readUTF();
        System.out.println(str);
        if(str.compareTo("1")==0){
            Screen scr=new Screen();
            this.dispose();
            scr.setVisible(true);
            dout.close();
        din.close();
        s.close();
        scr.set(Name.getText());
        System.out.println("hi bro");
        //scr.func();
                }
        else{
            JOptionPane.showMessageDialog(null, "Unsuccessful Connection", "InterCode", JOptionPane.INFORMATION_MESSAGE);
        }
//        dout.close();
//        din.close();
//        s.close();
//        this.dispose();
}catch(IOException e){
            System.out.println(0);           
    System.out.println(e);}  
    }//GEN-LAST:event_StartActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void CollegeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CollegeKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CollegeKeyTyped

    private void CollegeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CollegeKeyPressed
        // TODO add your handling code here:
        int k = evt.getKeyCode();
        System.out.println(k);
        System.out.println(VK_ESCAPE);
        if(k==VK_ESCAPE)
            device.setFullScreenWindow(null);
    }//GEN-LAST:event_CollegeKeyPressed

    private void RegnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegnoKeyPressed
System.out.println("Here");
        int k = evt.getKeyCode();
        System.out.println(k);
        System.out.println(VK_ESCAPE);
        if(k==VK_ESCAPE)
            device.setFullScreenWindow(null);
        if(k==122)
            device.setFullScreenWindow(this);        // TODO add your handling code here:
    }//GEN-LAST:event_RegnoKeyPressed

    private void NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyPressed
System.out.println("Here");
        int k = evt.getKeyCode();
        System.out.println(k);
        System.out.println(VK_ESCAPE);
        if(k==VK_ESCAPE)
            device.setFullScreenWindow(null);
        if(k==122)
            device.setFullScreenWindow(this);        // TODO add your handling code here:
    }//GEN-LAST:event_NameKeyPressed

    private void BranchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BranchKeyPressed
System.out.println("Here");
        int k = evt.getKeyCode();
        System.out.println(k);
        System.out.println(VK_ESCAPE);
        if(k==VK_ESCAPE)
            device.setFullScreenWindow(null);
        if(k==122)
            device.setFullScreenWindow(this);        // TODO add your handling code here:
    }//GEN-LAST:event_BranchKeyPressed

    private void StartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartKeyPressed
System.out.println("Here");
        int k = evt.getKeyCode();
        System.out.println(k);
        System.out.println(VK_ESCAPE);
        if(k==VK_ESCAPE)
            device.setFullScreenWindow(null);
        if(k==122)
            device.setFullScreenWindow(this);        // TODO add your handling code here:
    }//GEN-LAST:event_StartKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                firstscreen fs = new firstscreen();
                fs.setVisible(true);
                device.setFullScreenWindow(fs);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Branch;
    private javax.swing.JTextField College;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Regno;
    private javax.swing.JButton Start;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        System.out.println("Key Typed!!");
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        System.out.println("Here");
        int k = e.getKeyCode();
        System.out.println(k);
        System.out.println(VK_ESCAPE);
        if(k==VK_ESCAPE)
            device.setFullScreenWindow(null);
        if(k==122)
            device.setFullScreenWindow(this);
        
    }

    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        System.out.println("Key released");
    }
}
